version: '3'

services:
  gw:
    build: 
      context: ./gw
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - internal
    restart: always

  ps:
    build:
      context: ./productService
      dockerfile: Dockerfile
    container_name: product-service
    networks:
      - internal
    depends_on:
      - gw
    restart: always
  us:
    build:
      context: ./userService
      dockerfile: Dockerfile
    container_name: user-service
    networks:
      - internal
    depends_on:
      - gw
    restart: always
networks:
  internal:
    driver: bridge
